config/routes.rb
Homeforgrandma::Application.routes.draw do
  devise_for :users
  scope module: 'private' do
    namespace :my do
      resource :property, only: [:edit, :update], controller: 'properties' do
        member do
          get  :step1, to: 'properties#edit'
          post :step2, to: 'properties#step2'
        end
      end
    end

    resources :properties, only: [] do
      member do
        post    :like
      end
    end
  end

  resources :properties, only: [:show] do
    resource :messages, only: [:create]
  end
  resource  :contact, controller: 'contact', only: [:show, :create]

  # Static routes
  get '/about',               to: "home#about",             as: 'about'
  get '/searches',            to: "properties#searches",    as: 'searches'
  get '/locations/detail',    to: "home#location",          as: 'location'
  get  '/local-information',  to: 'home#local_information', as: 'local_information'


  root to: 'home#show'
end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id                      :integer          not null, primary key
#  user_id                 :integer
#  name                    :string(255)
#  address                 :string(255)
#  state_code              :string(255)
#  zip                     :string(255)
#  city                    :string(255)
#  phone_number            :string(255)
#  phone_number_2          :string(255)
#  types                   :text
#  description             :text
#  latitude                :float
#  longitude               :float
#  created_at              :datetime
#  updated_at              :datetime
#  license_number          :string(255)
#  capacity                :integer
#  care_services           :string(255)
#  feature_and_amenities   :string(255)
#  dinnings                :string(255)
#  buy_in_fee              :string(255)
#  add_person_fee          :string(255)
#  community_fee           :string(255)
#  respite_fee             :string(255)
#  caregivers_languages_1  :string(255)
#  caregivers_languages_2  :string(255)
#  resident_ethnics_1      :string(255)
#  resident_ethnics_2      :string(255)
#  property_manager_avatar :string(255)
#  vacancies               :string(255)
#  property_manager_name   :string(255)
#  include_service_charge  :boolean          default(FALSE)
#  accept_ssi              :boolean          default(FALSE)
#

class Property < ActiveRecord::Base
  include ExtProperty::Searchable
  extend Enumerize
  attr_accessor :vacant_vacility, :step # => Used For Multi Page Form


  # serialize attrubutes
  serialize :types, Array
  serialize :dinnings, Array
  serialize :care_services, Array
  serialize :feature_and_amenities, Array

  enumerize :types,                   in: Enum::Property::TYPES[:options],
                                      multiple: true
  enumerize :care_services,           in: Enum::Property::CARE_SERVICES[:options],
                                      multiple: true
  enumerize :feature_and_amenities,   in: Enum::Property::FEATURE_AND_AMENITIES[:options],
                                      multiple: true
  enumerize :caregivers_languages_1,  in: Enum::Property::CAREGIVERS_LANGUAGES[:options]
  enumerize :caregivers_languages_2,  in: Enum::Property::CAREGIVERS_LANGUAGES[:options]
  enumerize :resident_ethnics_1,      in: Enum::Property::RESIDENT_ETHNICS[:options]
  enumerize :resident_ethnics_2,      in: Enum::Property::RESIDENT_ETHNICS[:options]
  enumerize :dinnings,                in: Enum::Property::DINNINGS[:options],
                                      :multiple => true


  mount_uploader :property_manager_avatar, PropertyManagerAvatarUploader

  # relations
  belongs_to  :user
  has_many    :property_room_types
  has_many    :property_service_types
  has_many    :property_photos
  has_many    :messages


  # accept nested attributes
  accepts_nested_attributes_for :property_room_types,     allow_destroy: true, reject_if: Proc.new { |room_type| room_type["name"].blank? && room_type['_destroy'] == 'false' }
  accepts_nested_attributes_for :property_service_types,  allow_destroy: true, reject_if: Proc.new { |service_type| service_type["name"].blank? && service_type['_destroy'] == 'false' }
  accepts_nested_attributes_for :property_photos,         allow_destroy: true, reject_if: Proc.new { |photo| photo["photo"].blank? && photo['_destroy'] == 'false' }


  # Geocoding
  geocoded_by :address
  after_validation :geocode

  # validation
  validates :name,            presence: true
  validates :user,            presence: true
  validates :address,         presence: true
  validates :state_code,      presence: true
  validates :zip,             presence: true
  validates :city,            presence: true
  validates :phone_number,    presence: true
  validates :capacity,        presence: true
  validates :vacancies,       presence: true
  validates :types,           presence: true

  validates :property_manager_name,    presence: true
  validates :property_room_types,      presence: true, if: Proc.new { |p| ((p.step == 2) && p.new_record?)  }
  validates :property_service_types,   presence: true, if: Proc.new { |p| (p.include_service_charge.blank? && (p.step == 2)) || ((p.step == 2) && p.new_record?)}

  # callbacks
  before_save :assign_default_photo

  # return the first room types + service types price
  #
  def price_start_at
    room_type     = property_room_types.first
    service_type  = property_service_types.first

    return BigDecimal("0.0") if (room_type.blank? || service_type.blank?)
    BigDecimal(room_type.price_start_at.to_s) + BigDecimal(service_type.price_start_at.to_s)
  end

  def display_name_and_address
    [name, [address, city, state_code, zip].compact.uniq.join(', ')].join ' - '
  end


  # get primary photo or first photo as default
  # if blank, generate new record photo property (not saved / not persisted)
  #
  def default_photo
    @default_photo ||= if property_photos.present?
      property_photos.where(primary: true).first || property_photos.first
    else
      PropertyPhoto.new
    end
  end


  private

    # when create property, set first photo as primary if still no primary
    # if no photos exists, then leave as it
    #
    def assign_default_photo
      if property_photos.where(primary: true).blank?
        property_photo = property_photos.first
        # if photo exists
        if property_photo.present?
          property_photo.primary = true
          property_photo.save
        end
      end
    end

end

app/controllers/private/my/properties_controller.rb
class Private::My::PropertiesController < Private::ModuleController

  # GET - edit_my_property_path(:id)
  #
  def edit
    property
  end

  # POST - step1_my_properties_path
  def step2
    params[:property][:types] = "" if params[:property][:types].length == 1 && params[:property][:types][0] == ""
    property.attributes = property_params
    property.step = 1


    if property.save
      property.property_photos.build          if property.property_photos.blank?

      if property.property_room_types.length < 3
        if property.property_room_types.length == 0
          property.property_room_types.build(name: 'Small Bedroom')
          property.property_room_types.build(name: 'Medium Bedroom')
          property.property_room_types.build(name: 'Large Bedroom')
        else
          (3 - property.property_room_types.length).times do
            property.property_room_types.build
          end
        end
      end

      if property.property_service_types.length < 3
        if property.property_service_types.length == 0
          property.property_service_types.build(name: 'Low Level Care')
          property.property_service_types.build(name: 'Medium Level Care')
          property.property_service_types.build(name: 'High Level Care')
        else
          (3 - property.property_service_types.length).times do
            property.property_service_types.build
          end
        end
      end

    else
      flash[:error] = property.errors.full_messages
      render action: :edit
    end
  end

  # POST - step2_my_property_path(:id)
  #
  def update
    unless property.update_attributes property_params.merge({step: 2})
      flash[:error] = property.errors.full_messages
      render action: :step2
    end
  end


  private

    # We need to set it first, because for the current system,
    # each user will only have 1 property
    # if they want to add more, so please just register new one
    #
    def property
      # @property ||= current_user.properties.find params[:id]
      @property ||= current_user.properties.first
      @property ||= current_user.properties.new property_params
      @property
    end


    # Filter param property
    def property_params
      if params[:property].present?
        params.require(:property).permit(:name, :address, :city, :state_code, :zip, :phone_number, :phone_number_2, :vacancies, :accept_ssi, :include_service_charge,
                                         :add_person_fee, :buy_in_fee, :community_fee, :respite_fee, :capacity, :description,
                                         :resident_ethnics_1, :caregivers_languages_1, :caregivers_languages_2, :license_number,
                                         :resident_ethnics_2, :step, :types, :property_manager_name, :property_manager_avatar,
                                         :care_services         => [],
                                         :dinnings              => [],
                                         :types                 => [],
                                         :room_types            => [],
                                         :service_types         => [],
                                         :feature_and_amenities => [],
                                         :property_photos_attributes        => [:photo, :_destroy, :id, :primary],
                                         :property_room_types_attributes    => [:name, :price_start_at, :_destroy, :id],
                                         :property_service_types_attributes => [:name, :price_start_at, :_destroy, :id]
                                        )
      end
    end


end

app/controllers/private/properties_controller.rb
class Private::PropertiesController < Private::ModuleController

  # POST -
  #
  def like
    @status  = nil
    @success = if current_user.like_property?(property)
      @status = 'dislike'
      current_user.dislike_property!(property)
    else
      @status = 'like'
      current_user.like_property!(property)
    end
  end


  private

    # prepopulate property
    def property
      @property ||= Property.find params[:id]
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  # GET - property_path(:id)
  #
  def show
    property
    @message       = Message.new
    @staffs        = User.limit(10)
  end



  # GET - searches_path
  #
  def searches
    @property = Property.new property_params
    @properties = if params[:property].blank?
      params[:property] ||= {}
      Property.includes(:property_photos, :property_room_types, :property_service_types).
               order("RANDOM()").
               page(params[:page]).per(6)
    else
      Property.advance_search(params[:property].merge(:page => params[:page])).results
    end
  end


  private

    # preopulate selected property
    def property
      @property ||= Property.find params[:id]
    end

    # property params
    def property_params
      params.require(:property).permit(:name, :address, :types, :vacant_vacility, :accept_ssi, :caregivers_languages_2, :resident_ethnics_2,
                                       :care_services => [],
                                       :feature_and_amenities => []) if params[:property].present?
    end
end

app/helpers/private/my/properties_helper.rb
module Private::My::PropertiesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def property_types_button(property)
    html_string = ""

    property.types.each do |type|
      html_string += content_tag :div, class: "#{property_type_code(type)[:css]} content-color-box" do
        content_tag :h5 do
          property_type_code(type)[:code]
        end
      end
    end

    html_string.html_safe
  end

  def property_type_code(type)
    types = {
      'assisted_living'         => {:code => 'AL',  :css => 'color-box1',   :color => "green"},
      'independant_living'      => {:code => 'IL',  :css => 'color-box2',   :color => "blue"},
      'residential_care'        => {:code => 'RC',  :css => 'color-box3',   :color => "pink"},
      'memory_care_specialty'   => {:code => 'MC', :css => 'color-box4',   :color => "orange"},
      'ccrc'                    => {:code => 'CCRC', :css => 'color-box5',  :color => "pink2"}
    }
    types[type]
  end


end

app/views/properties/_advance_filter.html.haml
.filter-container
  .show-btn-container
    .show-filter-btn{value: ""} Show More Filters
  .hide-btn-container
    .hide-filter-btn Hide Filters
  .filters-container
    %ul{style: "list-style: none;"}
      %li.checkbox-container{style: "float: left; margin-left: -30px;"}
        %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
        %label{style: "color: white; font-family: MyriadPro; margin-left: 28px; margin-top: -23px;"} Assisted Living
      %li.checkbox-container{style: "float: left; background: #33A3D7; width: 178px;"}
        %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
        %label{style: "color: white; font-family: MyriadPro; margin-left: 28px; margin-top: -23px;"} Independant Living
      %li.checkbox-container{style: "float: left; background: #EE789F; width: 150px;"}
        %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
        %label{style: "color: white; font-family: MyriadPro; margin-left: 28px; margin-top: -23px;"} Residential Care
      %li.checkbox-container{style: "float: left; background: #F0890F; width: 130px;"}
        %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}/
        %label{style: "color: white; font-family: MyriadPro; margin-left: 28px; margin-top: -23px;"} Memory Care
      %li.checkbox-container{style: "float: left; background: #CA5656; width: 140px;"}
        %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
        %label{style: "color: white; font-family: MyriadPro; margin-left: 28px; margin-top: -23px;"} Nursing Home
      %li.checkbox-container{style: "float: left; background: #CE80DF; width: 140px; margin-right: 0px;"}
        %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
        %label{style: "color: white; font-family: MyriadPro; margin-left: 28px; margin-top: -23px;"} Counting Care

  .facility-container
    %p Types of Facilities
    %ul{style: "list-style: none;"}
      %li
        %input.icheck-me{checked: "checked", "data-color" => "green", "data-skin" => "square", id: "#input-1", type: "checkbox"}
        %label Assisted Living
        .color-box1
          %h5 AL
      %li
        %input#check1.icheck-me{"data-color" => "blue", "data-skin" => "square", type: "checkbox"}
        %label Independent Living
        .color-box2
          %h5 IC
      %li
        %input.icheck-me{checked: "checked", "data-color" => "orange", "data-skin" => "square", id: "#input-3", type: "checkbox"}
        %label Residential Care Home
        .color-box3
          %h5 RC
      %li
        %input#check1.icheck-me{"data-color" => "pink", "data-skin" => "square", type: "checkbox"}
        %label CCRC
        .color-box4
          %h5 CCRC
  .filters1-container
    %p Search Filters
    %ul{style: "list-style: none;"}
      %li
        %input#check1.icheck-me{"data-color" => "green", "data-skin" => "square", type: "checkbox"}
        %label Accepts Medicare
      %li
        %input#check1.icheck-me{checked: "checked", "data-color" => "blue", "data-skin" => "square", type: "checkbox"}
        %label Accepts SSI
      %li
        %input#check1.icheck-me{"data-color" => "orange", "data-skin" => "square", type: "checkbox"}
        %label Only Vacant Listings
      %li
        %input#check1.icheck-me{checked: "checked", "data-color" => "pink", "data-skin" => "square", type: "checkbox"}
        %label Memory Care
        .color-box5
  .filters2-container
    %ul{style: "list-style: none;"}
      %li
        %input#check1.icheck-me{checked: "checked", "data-color" => "purple", "data-skin" => "square", type: "checkbox"}
        %label Hospice/Palliative Care
      %li
        %input#check1.icheck-me{"data-color" => "red", "data-skin" => "square", type: "checkbox"}
        %label Allows Pets
    = succeed "\u{200b}" do
      .styled-select1
        %select.query-type{placeholder: "Search Radius", value: ""}
          %option Search Radius
          %option Short Option
          %option This Is A Longer Option

app/views/properties/_grid_list.html.haml
%ul#sg-list
  - properties.each do |property|
    %li
      %sub
        = link_to property_path(property) do
          = image_tag (property.default_photo).try(:photo).try(:thumb)
      %big
        %sup{class: (user_signed_in? && current_user.like_property?(property) ? 'active' : '')}
          = link_to "Like", like_property_path(property.id), :method => :post, :remote => true, :id => "grid-listing-like-#{property.id}", title: (user_signed_in? && current_user.like_property?(property) ? 'Remove from Favorites' : 'Save to Favorites')
        %span.lb
          - property.types.each do |type|
            - if type == 'assisted_living'
              %small.lb-bt.green AL
            - if type == 'independant_living'
              %small.lb-bt.blue IL
            - if type == 'memory_care_specialty'
              %small.lb-bt.orange MC
            - if type == 'residential_care'
              %small.lb-bt.pink RC
            - if type == 'ccrc'
              %small.lb-bt.pink CCRC

        / end class lb
        %h2= property.name
        %h3= property.city
        %p= truncate property.description, length: 150
      %span.value
        %small= number_to_currency(property.price_start_at, precision: 0)

app/views/properties/_list.html.haml
%ul#sl-cont-list
  - properties.each do |property|
    %li{'data-latitude' => property.latitude, 'data-longitude' => property.longitude, 'data-property-name' => property.name}
      %sub
        = link_to property_path(property) do
          = image_tag property.default_photo.try(:photo).try(:thumb)
      %big
        %sup{class: (user_signed_in? && current_user.like_property?(property) ? 'active' : '')}
          = link_to "Like", like_property_path(property.id), :method => :post, :remote => true, :id => "listing-like-#{property.id}", title: (user_signed_in? && current_user.like_property?(property) ? 'Remove from Favorites' : 'Save to Favorites')

        %span.lb
          - property.types.each do |type|
            - if type == 'assisted_living'
              %small.lb-bt.green AL
            - if type == 'independant_living'
              %small.lb-bt.blue IL
            - if type == 'memory_care_specialty'
              %small.lb-bt.orange MC
            - if type == 'residential_care'
              %small.lb-bt.pink RC
            - if type == 'ccrc'
              %small.lb-bt.pink CCRC
        / end class lb
        = link_to content_tag(:h2, property.name), property_path(property)
        %h3= property.city
        %p= truncate property.description, length: 200
      %span.value
        %small= number_to_currency(property.price_start_at, precision: 0)

app/views/properties/show.html.haml
#singlepage
  #sp-header
    %sup
      = link_to "Back to listing", searches_path
    %big
      %strong= number_to_currency(@property.price_start_at, precision: 0)
    %div
      %h2= @property.name
      %h3
        = @property.address.gsub(/(\. ?+)||(\s+)/, "") + ", "
        = @property.city + ", " + @property.state_code.to_s + ", "
        = @property.zip
      %span
        %small.like{class: (user_signed_in? && current_user.like_property?(@property) ? 'active' : '')}
          = link_to "Like", like_property_path(@property.id), :method => :post, :remote => true, :id => "detail-listing-like-#{@property.id}", title: (user_signed_in? && current_user.like_property?(@property) ? 'Remove from Favorites' : 'Save to Favorites')
        %small.time
          %a{href: "#", title: "Wait List"} Time
        - @property.types.each do |type|
          - object = property_type_code(type)
          %small.bt{class: object[:color]}= link_to object[:code], '#'
          &nbsp;
  / end id sp-header
  #sp-left
    #sliderFrame
      #slider
        - if @property.property_photos.present?
          - @property.property_photos.each do |pp|
            %li
              %a{class: "lazyImage"}
                = image_tag pp.photo.preview.url, :alt => @property.name
      #thumbs
        .slideshow-viewport
          - if @property.property_photos.present?
            - @property.property_photos.each do |pp|
              .thumb
                = image_tag pp.photo.preview.url

    / #cycle
    /   %ul#cycle-list
    /     - if @property.property_photos.present?
    /       - @property.property_photos.each do |pp|
    /         %li
    /           = image_tag pp.photo.preview.url, :alt => @property.name
    /           %img{alt: "Img", src: "/assets/_temp/11.jpg"}
    /     - else
    /       %li
    /         = image_tag PropertyPhoto.new.photo.preview.url, :alt => @property.name
    /         %img{alt: "Img", src: "/assets/_temp/11.jpg"}


    /   / end cycle-list
    /   %span#cycle-right Next
    /   %span#cycle-left Prev

    /   / %span#cycle-counter  
    / / end id cycle
    / #slideshow
    /   %a{href: "", class: "slideshow-btn"} 
    /     %i.icon.icon-left 
    /   .slideshow-viewport
    /     %ul#slideshow-list
    /       - if @property.property_photos.present?
    /         - @property.property_photos.each do |pp|
    /           %li.thumbnail
    /             %a{class: "media-photo", href: "#"}
    /               = image_tag pp.photo.preview.url, :alt => @property.name, :width => 72, :height => 72
    /       - else
    /         %li
    /           = image_tag PropertyPhoto.new.photo.preview.url, :alt => @property.name
    /           %img{alt: "Img", src: "/assets/_temp/11.jpg"}
    /   %a{href: "", class: "slideshow-btn"}
    /     %i.icon.icon-right

    #sp-container
      %ul#sp-tabs
        %li.t-overview.active
          %a{href: "#", title: "Overview"} Overview
        %li.t-pricing
          %a{href: "#", title: "Pricing"} Pricing
        %li.t-care
          %a{href: "#", title: "Care"} Care
        %li.t-features
          %a{href: "#", title: "Features"} Features
        %li.t-culture
          %a{href: "#", title: "Culture"} Map

      / end id sp-tabs
      #sp-content
        #sp-content-overview.tab-content
          %h2 Description
          %div.license-capacity-info
            %span.capacity
              Capacity:
              = @property.capacity.present? ? @property.capacity : 'N/A'
            %span.license
              Lisence number:
              = "#{(@property.license_number.present? ?  @property.license_number : 'N/A')}"
            .clear

          %p
            = @property.description
        / end id sp-content-overview
        #sp-content-pricing.tab-content
          .t1
            %strong.name Room Type
            %strong.price Price
            .claer
            %ul
              - @property.property_room_types.each do |room|
                %li
                  %span.name
                    %span.sp-c-f-i
                      %label
                        = room.name
                  %span.price
                    %span.sp-c-f-i
                      %label
                        = number_to_currency(room.price_start_at, precision: 0)

          .clear
          .t1
            %strong.name Service Type
            %strong.price Price
            .claer
            %ul
              - @property.property_service_types.each do |service|
                %li
                  %span.name
                    %span.sp-c-f-i
                      %label
                        = service.name
                  %span.price
                    %span.sp-c-f-i
                      %label
                        = number_to_currency(service.price_start_at, precision: 0)

          .clear
          .t1
            %strong.name Other Fees
            %strong.price Price
            .claer
            %ul
              %li
                %span.name
                  %span.sp-c-f-i
                    %label Buy In Fee
                %span
                  %span.price
                    %span.sp-c-f-i
                      %label
                        = number_to_currency(@property.buy_in_fee, precision: 0)
              %li
                %span.name
                  %span.sp-c-f-i
                    %label Spouse Fee/Month
                %span
                  %span.price
                    %span.sp-c-f-i
                      %label
                        = number_to_currency(@property.add_person_fee, precision: 0)
              %li
                %span.name
                  %span.sp-c-f-i
                    %label Community Fee/Month
                %span
                  %span.price
                    %span.sp-c-f-i
                      %label
                        = number_to_currency(@property.community_fee, precision: 0)
              %li
                %span.name
                  %span.sp-c-f-i
                    %label Respite Fee/Month
                %span.price
                  %span.sp-c-f-i
                    %label
                      = number_to_currency(@property.respite_fee, precision: 0)


            .clear
            %ul
              %li
                %label
                  %input{type: "checkbox", checked: (@property.accept_ssi), disabled: true}
                  We Accept SSI





        #sp-content-care.tab-content
          %h2 Care Services
          = property_checkboxes_for_singlepage(Enum::Property::CARE_SERVICES[:options], "care_services", 7, @property.care_services )

        #sp-content-features.tab-content
          %h2 Features & Amenities
          = property_checkboxes_for_singlepage(Enum::Property::FEATURE_AND_AMENITIES[:options], "feature_and_amenities", 4, @property.feature_and_amenities )
          - if @property.dinnings.present?
            %h2.t2 Dining & Culture
            %ul
              - Enum::Property::DINNINGS[:options].each do |dinning|
                %li
                  %label
                    %input{type: "checkbox", checked: (@property.dinnings.include?(dinning.to_s)), disabled: true}
                    = I18n.t("enumerize.property.dinnings.#{dinning}")

          .sp-content-features-info
            %strong Our Caregivers Speak (other than english)
            - if @property.caregivers_languages_1.present?
              %span.sp-c-f-i
                %label
                  %input{type: "checkbox", checked: true, disabled: true}
                  = @property.caregivers_languages_1_text
            - if @property.caregivers_languages_2.present?
              %span.sp-c-f-i
                %label
                  %input{type: "checkbox", checked: true, disabled: true}
                  = @property.caregivers_languages_2_text
            %strong Most of our Residents are
            - if @property.resident_ethnics_1.present?
              %span.sp-c-f-i
                %label
                  %input{type: "checkbox", checked: true, disabled: true}
                  = @property.resident_ethnics_1_text
            - if @property.resident_ethnics_2.present?
              %span.sp-c-f-i
                %label
                  %input{type: "checkbox", checked: true, disabled: true}
                  = @property.resident_ethnics_2_text

        / end id sp-content-features
        #sp-content-culture.tab-content
          %div#property_location{ :style => " width: 600px; height:400px; margin: 0px; padding: 0px", 'data-latitude' => @property.latitude, 'data-longitude' => @property.longitude, 'data-name' => @property.name}

        / end id sp-content-culture
      / end id sp-content
    / end id sp-container
    #sp-comments
      %ul#sp-c-tabs
        %li.t-meet.active
          %a{href: "#", title: "Meet Our Staff"} Meet Our Staff
        %li.t-test
          %a{href: "#", title: "Testimonials"} Testimonials
      / end id sp-c-tabs
      / #sp-c-content
      /   %ul
      /     - @staffs.each do |staff|
      /       %li
      /         %big
      /           %span
      /             = image_tag(staff.avatar.thumb.url, alt: "Avatar")
      /         %div
      /           %p Masih Bohong Bohongan, consectetur adipiscing elit. Nunc ut turpis sit amet risus euismod auctor euismod pretium nisi. Ut viverra, libero in pharetra posuere, erat nibh semper risus, id sodales neque eros in nisl. Nam sit amet sapien eleifend, blandit justo vel, convallis libero.
      /           %strong= staff.email
      / #sp-c-test
      /   %ul
      /     - @staffs.each do |staff|
      /       %li
      /         %div
      /           %p Masih Bohong Bohongan, consectetur adipiscing elit. Nunc ut turpis sit amet risus euismod auctor euismod pretium nisi. Ut viverra, libero in pharetra posuere, erat nibh semper risus, id sodales neque eros in nisl. Nam sit amet sapien eleifend, blandit justo vel, convallis libero.
      /           %strong= staff.email

      = render 'properties/sp_c_content'
      = render 'properties/sp_c_test'
  #sp-right
    = render_cell(:property, :contact_property_manager, :property_id => @property.id)
    = render_cell(:property, :nearby_listing)


= call_js_init("initDetailProperty();")