config/routes.rb
Homeforgrandma::Application.routes.draw do
  devise_for :users
  scope module: 'private' do
    namespace :my do
      resource :property, only: [:edit, :update], controller: 'properties' do
        member do
          get  :step1, to: 'properties#edit'
          post :step2, to: 'properties#step2'
        end
      end
    end

    resources :properties, only: [] do
      member do
        post    :like
      end
    end
  end

  resources :properties, only: [:show] do
    resource :messages, only: [:create]
  end
  resource  :contact, controller: 'contact', only: [:show, :create]

  # Static routes
  get '/about',               to: "home#about",             as: 'about'
  get '/searches',            to: "properties#searches",    as: 'searches'
  get '/locations/detail',    to: "home#location",          as: 'location'
  get  '/local-information',  to: 'home#local_information', as: 'local_information'


  root to: 'home#show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
     @properties = Property.order("created_at DESC").limit(3)
  end
end

app/views/home/_list.html.haml
%ul#sl-cont-list
  - properties.each do |property|
    %li{'data-latitude' => property.latitude, 'data-longitude' => property.longitude, 'data-property-name' => property.name}
      %sub
        = link_to property_path(property) do
          = image_tag property.default_photo.try(:photo).try(:thumb)
      %big
        %sup
          %a{href: '#', title: "Like"} Like
        %span.lb
          - property.types.each do |type|
            - if type == 'assisted_living'
              %small.lb-bt.green AL
            - if type == 'independant_living'
              %small.lb-bt.blue IL
            - if type == 'memory_care_specialty'
              %small.mc
                = image_tag "search/img-mc.png"
            - if type == 'residential_care'
              %small.lb-bt.pink RC
            - if type == 'ccrc'
              %small.lb-bt.pink CCRC
        / end class lb
        = link_to content_tag(:h2, property.name), property_path(property)
        %h3= property.city
        %p= truncate property.description, length: 200
      %span.value
        %small= number_to_currency(property.price_start_at, precision: 0)

app/views/home/about.html.haml
#about
  %h2 About Us
  #about-cont
    = image_tag "_temp/10.jpg"
    %p Finding a senior home for your loved ones can be a confusing and difficult process for families. It’s an important decision when you’re deciding on a second home for the ones you love. That’s why we’ve set out to create a tool to help you navigate through the many senior housing options that are out there.
    %p Coming from backgrounds in technology and senior housing we saw the need for an in depth and easy to use service that also rewards our customers for using the website!
    %p It’s a win-win situation. Let our family help yours. Welcome to Home For Grandma.

app/views/home/dummy.html.haml
.search-main
  .filter-container
    .show-btn-container
      .show-filter-btn{value: ""} Show More Filters
    .hide-btn-container
      .hide-filter-btn Hide Filters
    .filters-container
      %ul{style: "list-style: none;"}
        %li.checkbox-container{style: "float: left; margin-left: -30px;"}
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
          %label{style: "color: white; font-family: MyriadPro; margin-left: 6px;"} Assisted Living
        %li.checkbox-container{style: "float: left; background: #33A3D7; width: 178px;"}
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
          %label{style: "color: white; font-family: MyriadPro; margin-left: 6px;"} Independant Living
        %li.checkbox-container{style: "float: left; background: #EE789F; width: 150px;"}
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
          %label{style: "color: white; font-family: MyriadPro; margin-left: 6px;"} Residential Care
        %li.checkbox-container{style: "float: left; background: #F0890F; width: 130px;"}
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}/
          %label{style: "color: white; font-family: MyriadPro; margin-left: 6px;"} Memory Care
        %li.checkbox-container{style: "float: left; background: #CA5656; width: 140px;"}
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
          %label{style: "color: white; font-family: MyriadPro; margin-left: 6px;"} Nursing Home
        %li.checkbox-container{style: "float: left; background: #CE80DF; width: 140px; margin-right: 0px;"}
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}
          %label{style: "color: white; font-family: MyriadPro; margin-left: 6px;"} Counting Care
    .facility-container
      %p Types of Facilities
      %ul{style: "list-style: none;"}
        %li
          %input.icheck-me{checked: "checked", "data-color" => "yellow", "data-skin" => "square", id: "#input-1", type: "checkbox"}
          %label Assisted Living
          .color-box1
            %h5 AL
        %li
          %input#check1.icheck-me{"data-color" => "blue", "data-skin" => "square", type: "checkbox"}
          %label Independent Living
          .color-box2
            %h5 IC
        %li
          %input.icheck-me{checked: "checked", "data-color" => "orange", "data-skin" => "square", id: "#input-3", type: "checkbox"}
          %label Residential Care Home
          .color-box3
            %h5 RC
        %li
          %input#check1.icheck-me{"data-color" => "pink", "data-skin" => "square", type: "checkbox"}
          %label CCRC
          .color-box4
            %h5 CCRC
    .filters1-container
      %p Search Filters
      %ul{style: "list-style: none;"}
        %li
          %input#check1.icheck-me{"data-color" => "yellow", "data-skin" => "square", type: "checkbox"}
          %label Accepts Medicare
        %li
          %input#check1.icheck-me{checked: "checked", "data-color" => "blue", "data-skin" => "square", type: "checkbox"}
          %label Accepts SSI
        %li
          %input#check1.icheck-me{"data-color" => "orange", "data-skin" => "square", type: "checkbox"}
          %label Only Vacant Listings
        %li
          %input#check1.icheck-me{checked: "checked", "data-color" => "pink", "data-skin" => "square", type: "checkbox"}
          %label Memory Care
          .color-box5
    .filters2-container
      %ul{style: "list-style: none;"}
        %li
          %input#check1.icheck-me{checked: "checked", "data-color" => "purple", "data-skin" => "square", type: "checkbox"}
          %label Hospice/Palliative Care
        %li
          %input#check1.icheck-me{"data-color" => "red", "data-skin" => "square", type: "checkbox"}
          %label Allows Pets
      = succeed "\u{200b}" do
        .styled-select1
          %select.query-type{placeholder: "Search Radius", value: ""}
            %option Search Radius
            %option Short Option
            %option This Is A Longer Option
  #tabs.ui-tabs-nav.ui-tabs-panel
    %ul
      %li
        %a{href: "#tabs-1"} SEARCHED LOCATION
      %li
        %a{href: "#tabs-2"} GRID VIEW
      %li.tabs-right
        %a{href: "#tabs-3"} LOCAL INFO
    #tabs-1.content-tab
      .low-price-btn Low Prices First
      .exhibitions
        .place
          .stamp1
            .pic.pic1
          .content-middle
            .color-box1.content-color-box
              %h5 AL
            .color-box2.content-color-box
              %h5 IL
            .color-box5.content-color-box
            %br
            %p{style: "font-size: 18px; font-weight: 900; margin-top: 10px;"} Golden Oaks Senior Living
            %p{style: "font-size: 16px; font-weight: 800; color: #9B9B9B; margin-bottom: 5px;"} South Pasadena, CA
            %p{style: "font-size: 14px; font-weight: 600; color: #9B9B9B;"} Residents and their families appreciate the great energy of our dedicated and tenured team and our high-quality dining program.
          .dark-flag
            %p{style: "position: relative; margin: 0 0; left: 47px; top: 25px; font-size: 13px;"} FROM
            %br
            %p{style: "position: relative; margin: 0 0; left: 33px; top: 5px; font-size: 24px; font-weight: 900;"} $3000
        .place
          .stamp1
            .pic.pic2
          .content-middle
            .color-box1.content-color-box
              %h5 AL
            %br
            %p{style: "font-size: 18px; font-weight: 900; margin-top: 10px;"} Golden Oaks Senior Living
            %p{style: "font-size: 16px; font-weight: 800; color: #9B9B9B; margin-bottom: 5px;"} South Pasadena, CA
            %p{style: "font-size: 14px; font-weight: 600; color: #9B9B9B;"} Residents and their families appreciate the great energy of our dedicated and tenured team and our high-quality dining program.
          .dark-flag
            %p{style: "position: relative; margin: 0 0; left: 47px; top: 25px; font-size: 13px;"} FROM
            %br
            %p{style: "position: relative; margin: 0 0; left: 33px; top: 5px; font-size: 24px; font-weight: 900;"} $3000
        .place
          .stamp1
            .pic.pic3
          .content-middle
            .color-box3.content-color-box
              %h5 RC
            %br
            %p{style: "font-size: 18px; font-weight: 900; margin-top: 10px;"} Golden Oaks Senior Living
            %p{style: "font-size: 16px; font-weight: 800; color: #9B9B9B; margin-bottom: 5px;"} South Pasadena, CA
            %p{style: "font-size: 14px; font-weight: 600; color: #9B9B9B;"} Residents and their families appreciate the great energy of our dedicated and tenured team and our high-quality dining program.
          .dark-flag
            %p{style: "position: relative; margin: 0 0; left: 47px; top: 25px; font-size: 13px;"} FROM
            %br
            %p{style: "position: relative; margin: 0 0; left: 33px; top: 5px; font-size: 24px; font-weight: 900;"} $3000
        .place
          .stamp1
            .pic.pic4
          .content-middle
            .color-box1.content-color-box
              %h5 AL
            .color-box2.content-color-box
              %h5 IL
            .color-box3.content-color-box
              %h5 RC
            %br
            %p{style: "font-size: 18px; font-weight: 900; margin-top: 10px;"} Golden Oaks Senior Living
            %p{style: "font-size: 16px; font-weight: 800; color: #9B9B9B; margin-bottom: 5px;"} South Pasadena, CA
            %p{style: "font-size: 14px; font-weight: 600; color: #9B9B9B;"} Residents and their families appreciate the great energy of our dedicated and tenured team and our high-quality dining program.
          .dark-flag
            %p{style: "position: relative; margin: 0 0; left: 47px; top: 25px; font-size: 13px;"} FROM
            %br
            %p{style: "position: relative; margin: 0 0; left: 33px; top: 5px; font-size: 24px; font-weight: 900;"} $3000
        .place
          .stamp1
            .pic.pic5
          .content-middle
            .color-box1.content-color-box
              %h5 AL
            .color-box2.content-color-box
              %h5 IL
            .color-box3.content-color-box
              %h5 RC
            %br
            %p{style: "font-size: 18px; font-weight: 900; margin-top: 10px;"} Golden Oaks Senior Living
            %p{style: "font-size: 16px; font-weight: 800; color: #9B9B9B; margin-bottom: 5px;"} South Pasadena, CA
            %p{style: "font-size: 14px; font-weight: 600; color: #9B9B9B;"} Residents and their families appreciate the great energy of our dedicated and tenured team and our high-quality dining program.
          .dark-flag
            %p{style: "position: relative; margin: 0 0; left: 47px; top: 25px; font-size: 13px;"} FROM
            %br
            %p{style: "position: relative; margin: 0 0; left: 33px; top: 5px; font-size: 24px; font-weight: 900;"} $3000
        .place
          .stamp1
            .pic.pic6
          .content-middle
            .color-box1.content-color-box
              %h5 AL
            .color-box2.content-color-box
              %h5 IL
            .color-box3.content-color-box
              %h5 RC
            %br
            %p{style: "font-size: 18px; font-weight: 900; margin-top: 10px;"} Golden Oaks Senior Living
            %p{style: "font-size: 16px; font-weight: 800; color: #9B9B9B; margin-bottom: 5px;"} South Pasadena, CA
            %p{style: "font-size: 14px; font-weight: 600; color: #9B9B9B;"} Residents and their families appreciate the great energy of our dedicated and tenured team and our high-quality dining program.
          .dark-flag
            %p{style: "position: relative; margin: 0 0; left: 47px; top: 25px; font-size: 13px;"} FROM
            %br
            %p{style: "position: relative; margin: 0 0; left: 33px; top: 5px; font-size: 24px; font-weight: 900;"} $3000
      .map_div
      .expand-search
        %form#search-form{"accept-charset" => "UTF-8", action: "/search", method: "get"}
          .input-wrapper-map
            .expand-btn
            %input#map-q.ui-autocomplete-input{autocomplete: "off", name: "q", placeholder: "Expand Map", type: "text"}/
            %span
              %a#map-search-btn{href: "search/index"} Redo Search in Map
        .map-filter
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}/
          .color-box1{style: "margin-right: 10px;"}
            %h5 AL
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}/
          .color-box2{style: "margin-right: 10px;"}
            %h5 IC
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}/
          .color-box3{style: "margin-right: 10px;"}
            %h5 RC
          %input.icheck-me{checked: "checked", "data-color" => "grey", "data-skin" => "square", id: "", type: "checkbox"}/
          .color-box4{style: "margin-right: 0px; width: 55px;"}
            %h5 CCRC
      .pages
        .pre-btn{style: "font-family: Web;"}   <
        .pg-btn.green-btn{style: "margin-left: 20px; font-size: 14px; width: 18px;"}  1
        .pg-btn{style: "margin-left: 10px; font-size: 14px; width: 18px;"}  2
        .pg-btn{style: "margin-left: 10px; font-size: 14px; width: 18px;"}  3
        .dots{style: "margin-left: 10px;"} ...
        .pg-btn{style: "margin-left: 8px; margin-right: 20px; font-size: 14px; width: 18px;"}  8
        .pre-btn{style: "font-family: Web; width: 18px;"}   >
    #tabs-2.content-tab
      %p Content for Tab 2
    #tabs-3.content-tab
      %p Content for Tab 3

app/views/home/local_information.html.haml
#localinformation{style: "border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px; box-shadow: rgb(204, 204, 204) 2px 2px 10px;"}
  #content
    %h2{style: "border-top-left-radius: 2px; border-top-right-radius: 2px; border-bottom-right-radius: 2px; border-bottom-left-radius: 2px;"} Pasadena, CA
    #li-search
      %select{name: ""}
        %option{value: ""} Public Facilities
    / end id li-search
    %img{alt: "Img", src: "assets/_temp/05.jpg"}/
    %p Pasadena is a city in Los Angeles County, California, United States. As of 2010 United States Census, the population of Pasadena was 137,122, making it the 180th-largest city in the United States, down from 168th place in 2009.
    %p Pasadena is the ninth-largest city in Los Angeles County, and on June 19, 1886, became the fourth to be incorporated in Los Angeles County, after Anaheim (February 10, 1870) and Santa Ana (June 1, 1886), both of which were originally in Los Angeles County until Orange County was established in 1889. It is one of the primary cultural centers of the San Gabriel Valley.
    %p Although famous for hosting the annual Rose Bowl football game and Tournament of Roses Parade, Pasadena is also the home to many scientific and cultural institutions, including the California Institute of Technology (Caltech), the Jet Propulsion Laboratory, Fuller Theological Seminary, Art Center College of Design, the Pasadena Playhouse, the Norton Simon Museum of Art and the Pacific Asia Museum.
    %p
    %h3 Public Facilities
    %p
    %p
    %h4 Rose Bowl Stadium
    %p
    %p In addition to the annual New Year's Day Rose Bowl game and the BCS National Championship game every four years, the stadium is the home field for the UCLA Bruins football team and has hosted five Super Bowls. Important soccer matches include the 1984 Summer Olympics, the final game of the 1994 FIFA World Cup, and the final game of the 1999 FIFA Women's World Cup.
    %p The Rose Bowl stadium was the home ground for the Los Angeles Galaxy of Major League Soccer from the team's inception in 1996 until in 2003, it moved into the soccer-specific Home Depot Center in Carson, California. The venue additionally hosted the 1998 MLS Cup. Many concerts and other events have been held in the stadium, such as a U2 concert in 2009.
    %p
    %h4 Aquatic Center
    %p
    %p The Rose Bowl Aquatics Center is an aquatics facility located adjacent to the Rose Bowl Stadium. The pool hosted the final practices of the 2000 US Olympic swimming and diving team. In 2008, the facility held the U.S. National Diving Championships.
    %p
    %h4 Tennis Center
    %p
    %p The Rose Bowl Tennis Center, operated by the city of Pasadena, is located due south of the Rose Bowl stadium.
    %p
    %h3 Airports
    %p
    %p Bob Hope Airport (also known as Burbank-Glendale-Pasadena Airport) in nearby Burbank serves as the regional airport for Pasadena. The airport is owned and operated by the Burbank-Glendale-Pasadena Airport Authority. The airport is under the control of the governments of the three cities for which it is named. Most destinations from Bob Hope Airport are within the United States, so Los Angeles International Airport in Los Angeles and LA/Ontario International Airport in Ontario are also important airports less than an hour from Pasadena. Long Beach Airport in Long Beach, California, is about an hour's drive away. John Wayne Airport in Orange County, California, is slightly more than an hour’s drive away from Pasadena.
    %p
    %h3 Climate
    %p
    %p Pasadena has a hot-summer Mediterranean climate (Köppen climate classification Csa). Because of its position both higher and further inland than Los Angeles, it experiences slightly colder winters and slightly hotter summers. Winters are typically mild and wet, with heavy rains and January night temperature occasionally dipping just below freezing (daytime highs in winter typically fluctuate between the 60's and low 70's). Spring is consistently warm and temperatures increase gradually culminating in hot summers which last well into October. Fall is short and erratic; often cooler, rainy days will be followed by hot, dry ones.
    %img{alt: "Img", src: "assets/_temp/06.jpg"}/
    %p The wettest year was 1983 with 48.47 inches (1,231 mm) and the driest year was 1947 with 5.37 inches (136 mm). The most rainfall in one month was 19.70 inches (500 mm) in February 1980. The most rainfall in 24 hours was 7.70 inches (196 mm) on March 2, 1938. Pasadena averages 21 inches (530 mm) of rain a year, about 6 inches more than nearby Los Angeles due to the rain shadow effect created by the San Gabriel Mountains. Because of the slope on which the city is built, sewer lines in the city's northern section have been known to overflow spectacularly.
    %p Situated at the base of the San Gabriel Mountains, snow is known to fall occasionally in Pasadena. The heaviest snowfall in Pasadena history occurred on January 11, 1949; 6 inches fell at Pasadena's city hall and more than 12 inches (300 mm) fell in the foothills of the city.[78] The most recent snowfall in Pasadena was 1 inch (25 mm) on February 26, 2011.
    %p On November 30 and December 1, 2011, Pasadena, along with surrounding communities, was struck by a major windstorm caused by Santa Ana winds[citation needed]. The city suffered heavy damage with trees toppled, buildings damaged and even the roof of a gas station torn off. Some[who?] dubbed the event "Hurricane Rose".
    #li-footer
      %h2{style: "border-top-left-radius: 2px; border-top-right-radius: 2px; border-bottom-right-radius: 2px; border-bottom-left-radius: 2px;"} Surrouding Cities
      = succeed "," do
        %a{href: "", title: "Alhambra"} Alhambra
      = succeed "," do
        %a{href: "", title: "Arcadia"} Arcadia
      = succeed "," do
        %a{href: "", title: "San Marino"} San Marino
      %a{href: "", title: "Temple City"} Temple City
      and
      = succeed "." do
        %a{href: "", title: "Los Angeles"} Los Angeles
    / end id li-footer
  / end id content
  #sidebar
    %h2{style: "border-top-left-radius: 2px; border-top-right-radius: 2px; border-bottom-right-radius: 2px; border-bottom-left-radius: 2px;"} Weather for Pasadena, CA
    %img{alt: "Img", src: "assets/_temp/07.jpg"}/
    %h2{style: "border-top-left-radius: 2px; border-top-right-radius: 2px; border-bottom-right-radius: 2px; border-bottom-left-radius: 2px;"} Races in Pasadena, CA
    %img.imgneg{alt: "Img", src: "assets/_temp/08.jpg"}/
    %h2{style: "border-top-left-radius: 2px; border-top-right-radius: 2px; border-bottom-right-radius: 2px; border-bottom-left-radius: 2px;"} Population for Pasadena, CA
    %img{alt: "Img", src: "assets/_temp/09.jpg"}/
  / end id sidebar

app/views/home/location.html.haml
#localinformation
  #content
    %h2 Pasadena, CA
    #li-search
      %select{name: ""}
        %option{value: ""} Public Facilities

    = image_tag "_temp/05.jpg"
    %p Pasadena is a city in Los Angeles County, California, United States. As of 2010 United States Census, the population of Pasadena was 137,122, making it the 180th-largest city in the United States, down from 168th place in 2009.
    %p Pasadena is the ninth-largest city in Los Angeles County, and on June 19, 1886, became the fourth to be incorporated in Los Angeles County, after Anaheim (February 10, 1870) and Santa Ana (June 1, 1886), both of which were originally in Los Angeles County until Orange County was established in 1889. It is one of the primary cultural centers of the San Gabriel Valley.
    %p Although famous for hosting the annual Rose Bowl football game and Tournament of Roses Parade, Pasadena is also the home to many scientific and cultural institutions, including the California Institute of Technology (Caltech), the Jet Propulsion Laboratory, Fuller Theological Seminary, Art Center College of Design, the Pasadena Playhouse, the Norton Simon Museum of Art and the Pacific Asia Museum.
    %p
    %h3 Public Facilities
    %p
    %p    
    %h4 Rose Bowl Stadium
    %p    
    %p In addition to the annual New Year's Day Rose Bowl game and the BCS National Championship game every four years, the stadium is the home field for the UCLA Bruins football team and has hosted five Super Bowls. Important soccer matches include the 1984 Summer Olympics, the final game of the 1994 FIFA World Cup, and the final game of the 1999 FIFA Women's World Cup.
    %p The Rose Bowl stadium was the home ground for the Los Angeles Galaxy of Major League Soccer from the team's inception in 1996 until in 2003, it moved into the soccer-specific Home Depot Center in Carson, California. The venue additionally hosted the 1998 MLS Cup. Many concerts and other events have been held in the stadium, such as a U2 concert in 2009.
    %p
    %h4 Aquatic Center
    %p    
    %p The Rose Bowl Aquatics Center is an aquatics facility located adjacent to the Rose Bowl Stadium. The pool hosted the final practices of the 2000 US Olympic swimming and diving team. In 2008, the facility held the U.S. National Diving Championships.
    %p
    %h4 Tennis Center
    %p    
    %p The Rose Bowl Tennis Center, operated by the city of Pasadena, is located due south of the Rose Bowl stadium.
    %p
    %h3 Airports
    %p    
    %p Bob Hope Airport (also known as Burbank-Glendale-Pasadena Airport) in nearby Burbank serves as the regional airport for Pasadena. The airport is owned and operated by the Burbank-Glendale-Pasadena Airport Authority. The airport is under the control of the governments of the three cities for which it is named. Most destinations from Bob Hope Airport are within the United States, so Los Angeles International Airport in Los Angeles and LA/Ontario International Airport in Ontario are also important airports less than an hour from Pasadena. Long Beach Airport in Long Beach, California, is about an hour's drive away. John Wayne Airport in Orange County, California, is slightly more than an hour’s drive away from Pasadena.
    %p
    %h3 Climate
    %p    
    %p Pasadena has a hot-summer Mediterranean climate (Köppen climate classification Csa). Because of its position both higher and further inland than Los Angeles, it experiences slightly colder winters and slightly hotter summers. Winters are typically mild and wet, with heavy rains and January night temperature occasionally dipping just below freezing (daytime highs in winter typically fluctuate between the 60's and low 70's). Spring is consistently warm and temperatures increase gradually culminating in hot summers which last well into October. Fall is short and erratic; often cooler, rainy days will be followed by hot, dry ones.
    = image_tag "_temp/06.jpg"
    %p The wettest year was 1983 with 48.47 inches (1,231 mm) and the driest year was 1947 with 5.37 inches (136 mm). The most rainfall in one month was 19.70 inches (500 mm) in February 1980. The most rainfall in 24 hours was 7.70 inches (196 mm) on March 2, 1938. Pasadena averages 21 inches (530 mm) of rain a year, about 6 inches more than nearby Los Angeles due to the rain shadow effect created by the San Gabriel Mountains. Because of the slope on which the city is built, sewer lines in the city's northern section have been known to overflow spectacularly.
    %p Situated at the base of the San Gabriel Mountains, snow is known to fall occasionally in Pasadena. The heaviest snowfall in Pasadena history occurred on January 11, 1949; 6 inches fell at Pasadena's city hall and more than 12 inches (300 mm) fell in the foothills of the city.[78] The most recent snowfall in Pasadena was 1 inch (25 mm) on February 26, 2011.
    %p On November 30 and December 1, 2011, Pasadena, along with surrounding communities, was struck by a major windstorm caused by Santa Ana winds[citation needed]. The city suffered heavy damage with trees toppled, buildings damaged and even the roof of a gas station torn off. Some[who?] dubbed the event "Hurricane Rose".
    #li-footer
      %h2 Surrouding Cities
      = succeed "," do
        %a{href: "", title: "Alhambra"} Alhambra
      = succeed "," do
        %a{href: "", title: "Arcadia"} Arcadia
      = succeed "," do
        %a{href: "", title: "San Marino"} San Marino
        %a{href: "", title: "Temple City"} Temple City
      and
      = succeed "." do
        %a{href: "", title: "Los Angeles"} Los Angeles

  #sidebar
    %h2 Weather for Pasadena, CA
    = image_tag "_temp/07.jpg"
    %h2 Races in Pasadena, CA
    = image_tag "_temp/08.jpg"
    %h2 Population for Pasadena, CA
    = image_tag "_temp/09.jpg"

app/views/home/show.html.haml
#banner
  .container
    #banner-container
      #banner-watch
        = link_to 'Watch Our Video Intro', "http://www.youtube.com/watch?v=9A2nhjijhPs&feature=youtu.be", title: 'Watch our Video Intro', class: 'fancybox-media'

      #banner-find
        = form_for :property, url: searches_path, method: :get do |f|
          %fieldset
            %legend Find the perfect home for Grandma
            %label
              = f.text_field :address, placeholder: "Search by City, Zip, or Property", class: 'txt'
            %label.lb-list
              %span.green AL
              %span.blue IL
              %span.pink RC
              %span.orange MC
              %span.red NH
              %span.pink2 CCRC
            %label
              .select
                = f.select :types, options_from_collection_for_select( [OpenStruct.new( { :text => "All Types"})] + facility_type_for_select, :name, :text), {}
            %label
              %input.sbt{src: "/assets/banner/bt-find.png", type: "image"}
      / end id banner-find

#home-why
  .container
    %h2 Why Facilities Should Sign Up
    %ul
      %li#hw-1
        %strong $200 Reward or Charity Donation
        %p
          Duis eleifend elit non quam dictum quis dignissim dui eleifend. Vivamus sit amet urna nulla, bibendum aliquet urna.
          = succeed "Phasellus" do
            %br
      %li#hw-2
        %strong Share with your family
        %p
          Duis eleifend elit non quam dictum quis dignissim dui eleifend. Vivamus sit amet urna nulla, bibendum aliquet urna.
          %br
          Phasellus aliquet dignissim sem.
      %li#hw-3
        %strong Save & Waitlist
        %p
          Duis eleifend elit non quam dictum quis dignissim dui eleifend. Vivamus sit amet urna nulla, bibendum aliquet urna.
          %br
          Phasellus aliquet dignissim sem.

#home-featured
  .container
    %h2 Featured Listings
    %ul
      - @properties.each do |property|
        %li
          %em
            %span
              = link_to property_path(property) do
                = image_tag property.default_photo.try(:photo).try(:thumb_grid)

          %big
            = link_to content_tag(:h3, property.display_name_and_address), property_path(property)
            %p= truncate property.description, length: 200
            %span.first
              %strong Form:
              = number_to_currency(property.price_start_at, precision: 0)
            %span
              %strong Type:
              - property.types.each do |type|
                = type.text + " | "
            %span
              %strong Location:
              = property.city

= call_js_init("initSearchFieldType();")