config/routes.rb
Homeforgrandma::Application.routes.draw do
  devise_for :users
  scope module: 'private' do
    namespace :my do
      resource :property, only: [:edit, :update], controller: 'properties' do
        member do
          get  :step1, to: 'properties#edit'
          post :step2, to: 'properties#step2'
        end
      end
    end

    resources :properties, only: [] do
      member do
        post    :like
      end
    end
  end

  resources :properties, only: [:show] do
    resource :messages, only: [:create]
  end
  resource  :contact, controller: 'contact', only: [:show, :create]

  # Static routes
  get '/about',               to: "home#about",             as: 'about'
  get '/searches',            to: "properties#searches",    as: 'searches'
  get '/locations/detail',    to: "home#location",          as: 'location'
  get  '/local-information',  to: 'home#local_information', as: 'local_information'


  root to: 'home#show'
end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id                      :integer          not null, primary key
#  user_id                 :integer
#  name                    :string(255)
#  address                 :string(255)
#  state_code              :string(255)
#  zip                     :string(255)
#  city                    :string(255)
#  phone_number            :string(255)
#  phone_number_2          :string(255)
#  types                   :text
#  description             :text
#  latitude                :float
#  longitude               :float
#  created_at              :datetime
#  updated_at              :datetime
#  license_number          :string(255)
#  capacity                :integer
#  care_services           :string(255)
#  feature_and_amenities   :string(255)
#  dinnings                :string(255)
#  buy_in_fee              :string(255)
#  add_person_fee          :string(255)
#  community_fee           :string(255)
#  respite_fee             :string(255)
#  caregivers_languages_1  :string(255)
#  caregivers_languages_2  :string(255)
#  resident_ethnics_1      :string(255)
#  resident_ethnics_2      :string(255)
#  property_manager_avatar :string(255)
#  vacancies               :string(255)
#  property_manager_name   :string(255)
#  include_service_charge  :boolean          default(FALSE)
#  accept_ssi              :boolean          default(FALSE)
#

class Property < ActiveRecord::Base
  include ExtProperty::Searchable
  extend Enumerize
  attr_accessor :vacant_vacility, :step # => Used For Multi Page Form


  # serialize attrubutes
  serialize :types, Array
  serialize :dinnings, Array
  serialize :care_services, Array
  serialize :feature_and_amenities, Array

  enumerize :types,                   in: Enum::Property::TYPES[:options],
                                      multiple: true
  enumerize :care_services,           in: Enum::Property::CARE_SERVICES[:options],
                                      multiple: true
  enumerize :feature_and_amenities,   in: Enum::Property::FEATURE_AND_AMENITIES[:options],
                                      multiple: true
  enumerize :caregivers_languages_1,  in: Enum::Property::CAREGIVERS_LANGUAGES[:options]
  enumerize :caregivers_languages_2,  in: Enum::Property::CAREGIVERS_LANGUAGES[:options]
  enumerize :resident_ethnics_1,      in: Enum::Property::RESIDENT_ETHNICS[:options]
  enumerize :resident_ethnics_2,      in: Enum::Property::RESIDENT_ETHNICS[:options]
  enumerize :dinnings,                in: Enum::Property::DINNINGS[:options],
                                      :multiple => true


  mount_uploader :property_manager_avatar, PropertyManagerAvatarUploader

  # relations
  belongs_to  :user
  has_many    :property_room_types
  has_many    :property_service_types
  has_many    :property_photos
  has_many    :messages


  # accept nested attributes
  accepts_nested_attributes_for :property_room_types,     allow_destroy: true, reject_if: Proc.new { |room_type| room_type["name"].blank? && room_type['_destroy'] == 'false' }
  accepts_nested_attributes_for :property_service_types,  allow_destroy: true, reject_if: Proc.new { |service_type| service_type["name"].blank? && service_type['_destroy'] == 'false' }
  accepts_nested_attributes_for :property_photos,         allow_destroy: true, reject_if: Proc.new { |photo| photo["photo"].blank? && photo['_destroy'] == 'false' }


  # Geocoding
  geocoded_by :address
  after_validation :geocode

  # validation
  validates :name,            presence: true
  validates :user,            presence: true
  validates :address,         presence: true
  validates :state_code,      presence: true
  validates :zip,             presence: true
  validates :city,            presence: true
  validates :phone_number,    presence: true
  validates :capacity,        presence: true
  validates :vacancies,       presence: true
  validates :types,           presence: true

  validates :property_manager_name,    presence: true
  validates :property_room_types,      presence: true, if: Proc.new { |p| ((p.step == 2) && p.new_record?)  }
  validates :property_service_types,   presence: true, if: Proc.new { |p| (p.include_service_charge.blank? && (p.step == 2)) || ((p.step == 2) && p.new_record?)}

  # callbacks
  before_save :assign_default_photo

  # return the first room types + service types price
  #
  def price_start_at
    room_type     = property_room_types.first
    service_type  = property_service_types.first

    return BigDecimal("0.0") if (room_type.blank? || service_type.blank?)
    BigDecimal(room_type.price_start_at.to_s) + BigDecimal(service_type.price_start_at.to_s)
  end

  def display_name_and_address
    [name, [address, city, state_code, zip].compact.uniq.join(', ')].join ' - '
  end


  # get primary photo or first photo as default
  # if blank, generate new record photo property (not saved / not persisted)
  #
  def default_photo
    @default_photo ||= if property_photos.present?
      property_photos.where(primary: true).first || property_photos.first
    else
      PropertyPhoto.new
    end
  end


  private

    # when create property, set first photo as primary if still no primary
    # if no photos exists, then leave as it
    #
    def assign_default_photo
      if property_photos.where(primary: true).blank?
        property_photo = property_photos.first
        # if photo exists
        if property_photo.present?
          property_photo.primary = true
          property_photo.save
        end
      end
    end

end

app/controllers/private/my/properties_controller.rb
class Private::My::PropertiesController < Private::ModuleController

  # GET - edit_my_property_path(:id)
  #
  def edit
    property
  end

  # POST - step1_my_properties_path
  def step2
    params[:property][:types] = "" if params[:property][:types].length == 1 && params[:property][:types][0] == ""
    property.attributes = property_params
    property.step = 1


    if property.save
      property.property_photos.build          if property.property_photos.blank?

      if property.property_room_types.length < 3
        if property.property_room_types.length == 0
          property.property_room_types.build(name: 'Small Bedroom')
          property.property_room_types.build(name: 'Medium Bedroom')
          property.property_room_types.build(name: 'Large Bedroom')
        else
          (3 - property.property_room_types.length).times do
            property.property_room_types.build
          end
        end
      end

      if property.property_service_types.length < 3
        if property.property_service_types.length == 0
          property.property_service_types.build(name: 'Low Level Care')
          property.property_service_types.build(name: 'Medium Level Care')
          property.property_service_types.build(name: 'High Level Care')
        else
          (3 - property.property_service_types.length).times do
            property.property_service_types.build
          end
        end
      end

    else
      flash[:error] = property.errors.full_messages
      render action: :edit
    end
  end

  # POST - step2_my_property_path(:id)
  #
  def update
    unless property.update_attributes property_params.merge({step: 2})
      flash[:error] = property.errors.full_messages
      render action: :step2
    end
  end


  private

    # We need to set it first, because for the current system,
    # each user will only have 1 property
    # if they want to add more, so please just register new one
    #
    def property
      # @property ||= current_user.properties.find params[:id]
      @property ||= current_user.properties.first
      @property ||= current_user.properties.new property_params
      @property
    end


    # Filter param property
    def property_params
      if params[:property].present?
        params.require(:property).permit(:name, :address, :city, :state_code, :zip, :phone_number, :phone_number_2, :vacancies, :accept_ssi, :include_service_charge,
                                         :add_person_fee, :buy_in_fee, :community_fee, :respite_fee, :capacity, :description,
                                         :resident_ethnics_1, :caregivers_languages_1, :caregivers_languages_2, :license_number,
                                         :resident_ethnics_2, :step, :types, :property_manager_name, :property_manager_avatar,
                                         :care_services         => [],
                                         :dinnings              => [],
                                         :types                 => [],
                                         :room_types            => [],
                                         :service_types         => [],
                                         :feature_and_amenities => [],
                                         :property_photos_attributes        => [:photo, :_destroy, :id, :primary],
                                         :property_room_types_attributes    => [:name, :price_start_at, :_destroy, :id],
                                         :property_service_types_attributes => [:name, :price_start_at, :_destroy, :id]
                                        )
      end
    end


end

app/controllers/private/properties_controller.rb
class Private::PropertiesController < Private::ModuleController

  # POST -
  #
  def like
    @status  = nil
    @success = if current_user.like_property?(property)
      @status = 'dislike'
      current_user.dislike_property!(property)
    else
      @status = 'like'
      current_user.like_property!(property)
    end
  end


  private

    # prepopulate property
    def property
      @property ||= Property.find params[:id]
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  # GET - property_path(:id)
  #
  def show
    property
    @message       = Message.new
    @staffs        = User.limit(10)
  end



  # GET - searches_path
  #
  def searches
    @property = Property.new property_params
    @properties = if params[:property].blank?
      params[:property] ||= {}
      Property.includes(:property_photos, :property_room_types, :property_service_types).
               order("RANDOM()").
               page(params[:page]).per(6)
    else
      Property.advance_search(params[:property].merge(:page => params[:page])).results
    end
  end


  private

    # preopulate selected property
    def property
      @property ||= Property.find params[:id]
    end

    # property params
    def property_params
      params.require(:property).permit(:name, :address, :types, :vacant_vacility, :accept_ssi, :caregivers_languages_2, :resident_ethnics_2,
                                       :care_services => [],
                                       :feature_and_amenities => []) if params[:property].present?
    end
end

app/helpers/private/my/properties_helper.rb
module Private::My::PropertiesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def property_types_button(property)
    html_string = ""

    property.types.each do |type|
      html_string += content_tag :div, class: "#{property_type_code(type)[:css]} content-color-box" do
        content_tag :h5 do
          property_type_code(type)[:code]
        end
      end
    end

    html_string.html_safe
  end

  def property_type_code(type)
    types = {
      'assisted_living'         => {:code => 'AL',  :css => 'color-box1',   :color => "green"},
      'independant_living'      => {:code => 'IL',  :css => 'color-box2',   :color => "blue"},
      'residential_care'        => {:code => 'RC',  :css => 'color-box3',   :color => "pink"},
      'memory_care_specialty'   => {:code => 'MC', :css => 'color-box4',   :color => "orange"},
      'ccrc'                    => {:code => 'CCRC', :css => 'color-box5',  :color => "pink2"}
    }
    types[type]
  end


end

app/views/private/my/properties/_form_step1.html.haml
= f.input :step, :as => :hidden, :input_html => { :value => 1 }
.info-left
  %h2 General Info
  %fieldset
    %label.txt
      %span
        Facility Name
        = mark_required(@property, :name)
      = f.input :name, :label => false
    %label.txt
      %span
        Facility Address
        = mark_required(@property, :address)
      = f.input :address, :label => false
    %big
      %label.lb30
        %span
          City
          = mark_required(@property, :city)
        = f.input :city, :label => false
      %label.lbselect
        %span
          State
          = mark_required(@property, :state_code)
        %small.select
          = f.input :state_code, :as => :select, :collection => state_code_to_select , :label => false

      %label.lb20
        %span
          Zip
          = mark_required(@property, :zip)
        = f.input :zip, as: :string, :label => false
    %label.txt
      %span
        Phone Number
        = mark_required(@property, :phone_number)
      = f.input :phone_number, as: :string, :label => false
    %label.txt
      %span
        Facility Manager Name
        = mark_required(@property, :property_manager_name)
      = f.input :property_manager_name, :label => false
    %label.txt.camera
      %span
        Facility Manager Photo
        = mark_required(@property, :property_manager_avatar)
      = f.input :property_manager_avatar, :label => false
      %small
        %a{href: "", title: "Camera"} Camera
    %big
      %label.lb20
        %span
          Capacity
          = mark_required(@property, :capacity)
        = f.input :capacity, as: :string, label: false
      %label.lb20
        %span
          Vacancies
          = mark_required(@property, :vacancies)
        = f.input :vacancies, as: :string, label: false
      %label.lb20
        %span
          Lic Number
          = mark_required(@property, :license_number)
        = f.input :license_number, as: :string, label: false
    .radio1
      %h3
        Room Type
        = mark_required(@property, :types)
      = f.input :types, as: :check_boxes_em_label, :label => false

.info-right
  .radio2
    %h2.mb
      Features & Amenities
      = mark_required(@property, :feature_and_amenities)
    %fieldset
      = f.input :feature_and_amenities, as: :check_boxes_em_label, :label => false, :collection_wrapper_tag => :em
  .radio2
    %h2
      Care Services
      = mark_required(@property, :care_services)
    %fieldset
      = f.input :care_services, as: :check_boxes_em_label, :label => false
  .radio3
    %h2
      Dining & Culture
      = mark_required(@property, :dinnings)
    .radio3-l
      %fieldset
        = f.input :dinnings, as: :check_boxes_em_label, :label => false
    / end class radio3-l
    .radio3-r
      %big
        %fieldset
          %label
            %span
              Our Employees Speak
              = mark_required(@property, :caregivers_languages_1)
            = f.input :caregivers_languages_1, as: :select, :label => false
            = f.input :caregivers_languages_2, as: :select,:label => false
          %label
            %span
              Most of our Residents are
              = mark_required(@property, :resident_ethnics_1)
            = f.input :resident_ethnics_1, as: :select,:label => false
            = f.input :resident_ethnics_2, as: :select,:label => false
.popup-cont-footer.clear
  / %input.bt.bt-next1{type: "submit", value: "Next"}/
  = f.submit class: "bt", value: "Next"
  %strong Step 1 of 2

app/views/private/my/properties/edit.html.haml
#singlepage
  #new-propery-form
    - if @property.errors.present?
      %span.m Please check following error messages:
      %ul.alert-box
        - @property.errors.full_messages.each do |message|
          %li= message

    = simple_form_for @property, url: step2_my_property_path, method: 'post', html: {multipart: true}  do |f|
      = render 'form_step1', f: f, property: @property

= call_js_init("initFormPropertyStep1();")

app/views/private/my/properties/message.html.haml
   %h2 Thank You for Registering
    %p.st We area Launching in Summer 2014!
    %p.ss Keep on eye on your Inboxes for exciting updates and announcements!
    %p.sy
      If you did NOT complete your registration this time or would
      %br>/
      like to add more photos later, just come back and login.
      %span 1. Would you prefer to pay our referral fee by credit/debit card?
      %label
        %input{name: "card", type: "radio"}/
        %small Yes
      %label
        %input{name: "card", type: "radio"}/
        %small No

      %input.bt{type: "submit", value: "Submit"}/
      %small or
      %input.bt{type: "submit", value: "Register Another Facility"}/
      %span
        We value your Feedback & suggestion!
        %a{href: "", title: "Contact Us"} Contact Us

app/views/private/my/properties/step2.html.haml
#singlepage
  #new-propery-form{:style => ""}


    - if @property.errors.present?
      %span.m Please check following error messages:
      %ul.alert-box
        - @property.errors.full_messages.each do |message|
          %li= message

    = simple_nested_form_for @property, url: my_property_path, html: {multipart: true} do |f|
      = @step1_data
      = f.input :step, :as => :hidden, :input_html => { :value => 2 }
      .price-l
        %h2
          Plan & Pricing
        %fieldset
          %big
            %label
              %span
                Buy-in Fee
                = mark_required(@property, :buy_in_fee)
              = f.input :buy_in_fee, label: false, placeholder: "$"
            %label
              %span
                Spouse Fee/Month
                = mark_required(@property, :add_person_fee)
              = f.input :add_person_fee, label: false, placeholder: "$"
            %label
              %span
                Community Fee/Month
                = mark_required(@property, :community_fee)
              = f.input :community_fee, label: false, placeholder: "$"
            %label
              %span
                Respite Fee/Month
                = mark_required(@property, :respite_fee)
              = f.input :respite_fee, label: false, placeholder: "$"
            %label
              %small
                = f.input :accept_ssi, :class => "checkbox", :label => false, inline_label: true, :label => "Accepts SSI"
                = mark_required(@property, :accept)
          #room-type

            .list-header
              %span.lh-1
                Room Type
                = mark_required(@property, :property_room_types)
              %span.lh-2 Price

            = f.fields_for :property_room_types do |prt_f|
              .list
                %label.l1
                  = prt_f.text_field :name, placeholder: "Small Bedroom"

                %label.l2
                  = prt_f.text_field :price_start_at, placeholder: "$"
                = prt_f.link_to_remove content_tag(:span, "&times;".html_safe, class: "delete")
            %small.add
              = f.link_to_add "Add a Room Type", :property_room_types
            %labeL
              %small
                = f.input :include_service_charge, :label_html => { :style => "color:#868585;" }, :label => false, inline_label: true, :label => "Room Type Includes Service Charge"
          #service-types
            .list-header
              %span.lh-1
                Service Type
                = mark_required(@property, :property_service_types)
              %span.lh-2 Price
              = f.fields_for :property_service_types do |prt_f|
                .list
                  %label.l1
                    = prt_f.text_field :name, placeholder: "Low Level Care"
                  %label.l2
                    = prt_f.text_field :price_start_at, placeholder: "$"
                  = prt_f.link_to_remove content_tag(:span, "&times;".html_safe, class: "delete")
                  %br
                  %br
              %small.add
                = f.link_to_add "Add a Service Type", :property_service_types

      .price-r
        %fieldset
          %legend
          %h2
            Description
            = mark_required(@property, :description)
          = f.text_area :description
          %h2
            Photos
            = mark_required(@property, :property_photos)
          %label
            %span.txt Select one main listing photo
          .clear
          .photos-field-container
            = f.fields_for :property_photos do |pp|
              .photo-primary
                = pp.input :primary, class: 'checkbox', label: false
              .photo-drag
                - if pp.object.photo.present?
                  .photo-avatar
                    = image_tag pp.object.photo.thumb.url, size: "70x58"
                    = pp.link_to_remove content_tag(:span, "&times;".html_safe, class: "delete")
                - else
                  .photo-input
                    = pp.file_field :photo, value: pp.object.try(:photo)
                    = pp.link_to_remove content_tag(:span, "&times;".html_safe, class: "delete")
              .clear

            // link to add more photo
            = f.link_to_add "Add a photo", :property_photos


      / end class price-r
      .popup-cont-footer.clear
        = f.submit class: "bt bt-next2", value: "Submit"
        %strong
          Step 2 of 2
        = link_to "<input class = \"bt bt-back\" value = \"Back\" style = \"width: 30px; margin-right: 15px\" />".html_safe, step1_my_property_path

= call_js_init("initFormPropertyStep2();")

app/views/private/my/properties/update.html.haml
#success-register-property
  .popup-ok{style: "border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px;"}
    %h2 Thank You for Registering
    %p.st We Are Launching in Summer 2014!
    %p.ss Keep on eye on your Inboxes for exciting updates and announcements!
    %p.sy
      If you did NOT complete your registration this time or would
      %br
      like to add more photos later, just come back and login.
    .ok-card
      %span 1. Would you prefer to pay our referral fee by credit/debit card?
      %label
        %input{name: "card", type: "radio"}
        %small Yes
      %label
        %input{name: "card", type: "radio"}
        %small No
    / end class ok-card
    .ok-bt
      = link_to property_path(current_user.properties.first) do
        %input.bt{style: "border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px;", type: "submit", value: "View Your Listing"}
      %small or
      = link_to edit_my_property_path do
        %input.bt{style: "border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px;", type: "submit", value: "Edit your Facility"}
      %span
        We value your Feedback & suggestion!
        = link_to 'Contact Us', '#', title: 'Contact Us'
    .clear
    / end class ok-bt
  / end class popup-cont